"""initial_schema

Revision ID: 775f60f34708
Revises: 
Create Date: 2026-09-26 16:03:48.739494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775f60f34708'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('standards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('bis_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_category'), 'standards', ['category'], unique=False)
    op.create_index(op.f('ix_standards_is_deleted'), 'standards', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_standards_standard_code'), 'standards', ['standard_code'], unique=True)
    op.create_index(op.f('ix_standards_status'), 'standards', ['status'], unique=False)
    op.create_index(op.f('ix_standards_title'), 'standards', ['title'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('certification_type', sa.String(length=100), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('qco_order_number', sa.String(length=255), nullable=True),
    sa.Column('qco_date', sa.DateTime(), nullable=True),
    sa.Column('applicable_ministry', sa.String(length=255), nullable=True),
    sa.Column('compliance_category', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_certification_type'), 'certifications', ['certification_type'], unique=False)
    op.create_index(op.f('ix_certifications_compliance_category'), 'certifications', ['compliance_category'], unique=False)
    op.create_index(op.f('ix_certifications_is_deleted'), 'certifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_certifications_is_mandatory'), 'certifications', ['is_mandatory'], unique=False)
    op.create_index(op.f('ix_certifications_standard_id'), 'certifications', ['standard_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('standard_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_standard_id', sa.String(length=36), nullable=False),
    sa.Column('target_standard_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('clause_reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_references_relationship_type'), 'standard_references', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_standard_references_source_standard_id'), 'standard_references', ['source_standard_id'], unique=False)
    op.create_index(op.f('ix_standard_references_target_standard_id'), 'standard_references', ['target_standard_id'], unique=False)
    op.create_table('standard_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('superseded_date', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_version_id', sa.String(length=36), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_version_id'], ['standard_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_versions_is_current'), 'standard_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_standard_versions_standard_id'), 'standard_versions', ['standard_id'], unique=False)
    op.create_index(op.f('ix_standard_versions_year'), 'standard_versions', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('amendments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_version_id', sa.String(length=36), nullable=False),
    sa.Column('amendment_number', sa.Integer(), nullable=False),
    sa.Column('amendment_code', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('impact_clauses', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amendments_standard_version_id'), 'amendments', ['standard_version_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_created_by_id'), 'projects', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_projects_department_id'), 'projects', ['department_id'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tender_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuing_authority', sa.String(length=255), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_is_deleted'), 'tenders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenders_issuing_authority'), 'tenders', ['issuing_authority'], unique=False)
    op.create_index(op.f('ix_tenders_project_id'), 'tenders', ['project_id'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_tender_number'), 'tenders', ['tender_number'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tender_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('ocr_applied', sa.Boolean(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash_sha256'), 'documents', ['file_hash_sha256'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_tender_id'), 'documents', ['tender_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tender_id', sa.String(length=36), nullable=True),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('why_justification', sa.Text(), nullable=False),
    sa.Column('relationship_summary', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('certification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['standard_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_is_deleted'), 'recommendations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_recommendations_match_score'), 'recommendations', ['match_score'], unique=False)
    op.create_index(op.f('ix_recommendations_project_id'), 'recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_recommendations_standard_id'), 'recommendations', ['standard_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_tender_id'), 'recommendations', ['tender_id'], unique=False)
    op.create_index(op.f('ix_recommendations_version_id'), 'recommendations', ['version_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('standard_id', sa.String(length=36), nullable=True),
    sa.Column('source_text_snippet', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('clause_number', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_recommendation_id'), 'evidence', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_evidence_standard_id'), 'evidence', ['standard_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_action'), 'reviews', ['action'], unique=False)
    op.create_index(op.f('ix_reviews_reason_code'), 'reviews', ['reason_code'], unique=False)
    op.create_index(op.f('ix_reviews_recommendation_id'), 'reviews', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_recommendation_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reason_code'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_action'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_evidence_standard_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_recommendation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_recommendations_version_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_tender_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_standard_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_project_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_match_score'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_is_deleted'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_documents_tender_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_tenders_tender_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_project_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_issuing_authority'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_is_deleted'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_department_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_amendments_standard_version_id'), table_name='amendments')
    op.drop_table('amendments')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standard_versions_year'), table_name='standard_versions')
    op.drop_index(op.f('ix_standard_versions_standard_id'), table_name='standard_versions')
    op.drop_index(op.f('ix_standard_versions_is_current'), table_name='standard_versions')
    op.drop_table('standard_versions')
    op.drop_index(op.f('ix_standard_references_target_standard_id'), table_name='standard_references')
    op.drop_index(op.f('ix_standard_references_source_standard_id'), table_name='standard_references')
    op.drop_index(op.f('ix_standard_references_relationship_type'), table_name='standard_references')
    op.drop_table('standard_references')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_certifications_standard_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_is_mandatory'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_is_deleted'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_compliance_category'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_certification_type'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_standards_title'), table_name='standards')
    op.drop_index(op.f('ix_standards_status'), table_name='standards')
    op.drop_index(op.f('ix_standards_standard_code'), table_name='standards')
    op.drop_index(op.f('ix_standards_is_deleted'), table_name='standards')
    op.drop_index(op.f('ix_standards_category'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
